### ISSUE TITLE
Clarifying single file moon component usage in Readme.md

### ISSUE THREAD

**Issue by skilfullycurled** [KingPixil/moon-component-compiler#2]
Hi,

First, great library.  So easy to understand.  Simple.  For a beginner, it's really nice to be able to work with some of these more advanced framework techniques without getting bogged down into the minutia.

Would it be possible to have some clarification on the usage of single file moon components detailed in the README.md?

Given the following:

> To compile a single file component (a .moon file), you can do:
> ```
> const compile = require("moon-component-compiler");
> const compiled = compile("Head", component, {
>   hotReload: true
> });
> ```

1. In the example, what is the name of the .moon file in question (e.g. Head.moon, component.moon)?

2. The [documentation](http://moonjs.ga/docs/compiler.html) on the compile function does not list the parameters you can pass to the compile function.  However, it would seem from the moon-component-compiler [source](https://github.com/kbrsh/moon-component-compiler/blob/4991e112ae8e57f6a82f7109e646bea70d9aba5c/index.js#L13) that you can pass:

`const compile = (name, component, options) => {`

How do the name and component relate to the .moon file?  What options are available?

3. Does the single component file need to be imported?  In a vue situation one might do:

```
import Head from './Head.vue';

new Vue({
  el: '#app',
  template: '<Head/>',
  components: { Head }
})
```
Thanks so much for all of your work on this!

**Comment by kbrsh** [comment]
Glad you like it! This is mostly an internal module used by [Moonify](https://github.com/kbrsh/moonify) for use with the CLI template. It isn't intended to be an API for the user, and the short set of notes I added is just for anyone who wants to dig into the compiler.

I'd recommend generating a project with the CLI, as this mainly takes an input (`.moon` file), and returns output JavaScript code.

1. `name` -> the name of the component
2. `component` -> component text
3. `options` -> object with one valid property `development` of type boolean. It determines if the hot reloading modules are used or not.

**Comment by skilfullycurled** [comment]
Ah, okay.  I'm still a bit confused but I'll re-post in the main moon.js library since it's not really an issue related to this particular one.

Thanks!
